// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPCfjwUgW7INA93TVj-NUr_6mXWyeTS0U',
    appId: '1:412740132284:web:3ddfd9f4a29f7e60479fb9',
    messagingSenderId: '412740132284',
    projectId: 'crm-staffing-111b7',
    authDomain: 'crm-staffing-111b7.firebaseapp.com',
    storageBucket: 'crm-staffing-111b7.firebasestorage.app',
    measurementId: 'G-6G56MDE62F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSqg9-UvpGo-WvyjWxQFkkqA7qCx-bTN8',
    appId: '1:412740132284:android:0703889e485105bb479fb9',
    messagingSenderId: '412740132284',
    projectId: 'crm-staffing-111b7',
    storageBucket: 'crm-staffing-111b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPxJS0_ROMnxThLjEBiNDLEEMSDLMeRbA',
    appId: '1:412740132284:ios:eaf0e9e360f3f5b3479fb9',
    messagingSenderId: '412740132284',
    projectId: 'crm-staffing-111b7',
    storageBucket: 'crm-staffing-111b7.firebasestorage.app',
    iosBundleId: 'com.sansynapse.hrApp',
  );
}
